#
# Makefile for golang-socketio
#
usage:
	@echo "make [edit|run]"

edit e:
	@echo "make (edit) [client|server]"

edit-client ec:
	vi client.go

edit-server es:
	vi server.go

run r:
	@echo "make (run) [client|server]"

run-client rc:
	go run client.go

run-server rs:
	go run server.go

